version: 2
sources:
  - name: raw_data
    description: "Raw data source for NYC taxi rides"
    database: taxi_rides_ny
    schema: prod
    tables:
      - name: yellow_tripdata
        description: "Yellow taxi trip data"
        columns:
          - name: vendorid
            description: |
              A code indicating the provider associated with the trip record.
                1: Creative Mobile Technologies, LLC
                2: VeriFone Inc.
                4: Unknown/Other
            data_type: integer
            meta:
              pii: false
              owner: data_engineering_team
              importance: high
              formatting: none
      - name: green_tripdata
        description: "Green taxi trip data"